name: C++ Build and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'cpp/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - '.github/workflows/cpp-build.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'cpp/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - '.github/workflows/cpp-build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16'

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      run: ctest --output-on-failure --config ${{ matrix.build_type }}

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16'

    - name: Configure CMake with strict warnings
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build with warnings as errors
      run: cmake --build build

    - name: Check for warnings
      run: |
        if cmake --build build 2>&1 | grep -i warning; then
          echo "Build contains warnings"
          exit 1
        else
          echo "Build completed without warnings"
        fi